#ifndef CUBE3D_H
# define CUBE3D_H

#include "cube3d_bonus.h"

// function declarations we copied
char	*trim_whitespace(char *str);
const	char *get_cardinal_direction(float x, float y);
float	calc_rotation_angle(int dx, float speed);
float	calculate_dynamic_buffer(t_player *player, float base_speed);
float	calculate_new_position_x(t_game *game, float dx, float bump_distance);
float	calculate_new_position_y(t_game *game, float dy, float bump_distance);
float	calculate_screen_shake(t_game *game, int current_frame);
float	random_float(t_game *game);
float	vector2d_distance_squared(t_vector2d a, t_vector2d b);
int	**initialize_array(int x, int y);
int	all_paths_set(t_game *game);
int	assign_texture(char **words, char **path, char *texture);
int	assign_textures(t_game *game, char **words);
int	check_invalid_rgb(char *word);
int	check_line(t_game *game, char *line, int *map_start);
int	check_map_boundaries(t_game *game);
int	check_order_in_column(int **array, int col, int row_count, int direction);
int	check_order_in_row(int **array, int row, int col_count, int direction);
int	check_player_position_helper(t_game *game, int i, int j, int *player_found);
int	check_player_postion_and_map_char(t_game *game);
int	count_words_from_array(char **words);
int	create_collectibles(t_game *game);
int	create_extraction(t_game *game);
int	create_game_struct(t_game **game, int is_bonus);
int	create_map(t_game *game);
int	create_player(t_game *game);
int	create_supplies(t_game *game);
int	findAvailableSource(void);
int	ft_isinteger(char *number);
int	get_texture_color(t_texture *texture, int x, int y);
int	handle_error(const char *message, int error_code);
int	handle_first_loop(t_game *game);
int	handle_second_loop(t_game *game);
int	initializeAudio(void);
int	is_player_close_to_collectible(t_game *game);
int	is_player_close_to_extract(t_game *game);
int	loop_thru_line_in_map_array(t_game *game);
int	parse_char_to_int(char chars);
int	parse_floor_sky_rgb(t_game *game);
int	parse_line_to_map_array(char *line, t_game *game, int *map_line);
int	parse_map_to_array(t_game *game);
int	playAudioFileWithDelay(const char *filename, float delayInSeconds);
int	prepare_second_loop(t_game *game);
int	random_0_to_3(t_game *game);
int	read_cub_texture_and_analyze_map(t_game *game);
int	rgb_to_hex_int(int red, int green, int blue);
int	select_frame_to_render(t_game *game);
int	stopAudioFile(const char *filename);
int	texture_error_handling(t_game *game);
int	validate_map(int *valid, int **array, int row_count, int col_count);
int	apply_bump(t_game *game, float newX, float newY);
int	bonus_game_loop(t_game *game);
int	bonus_game_loop_0(t_game *game);
int	bonus_game_loop_1(t_game *game);
int	bonus_game_loop_2(t_game *game);
int	bonus_game_loop_3(t_game *game);
int	bonus_game_loop_4(t_game *game);
int	calculate_enemy_count(t_game *game);
int	calculate_sprite_screen_x(t_game *game, float transformX, float transformY);
int	calculate_supplies(t_game *game);
int	close_hook(t_game *game);
int	core_game_loop(t_game *game);
int	create_enemies(t_game *game);
int	create_strike(t_game *game);
int	detect_collision(t_game *game, float newX, float newY);
int	find_closest_supply(t_game *game);
int	find_supply_on_player_tile(t_game *game);
int	ft_key_press(int keycode, t_game *game);
int	ft_key_release(int keycode, t_game *game);
int	get_current_frame(struct timeval *start_time);
int	get_current_frame_outro(struct timeval *start_time);
int	get_floor_texture_color(t_texture *texture, int x, int y);
int	get_min_starting_index(t_strike *strike);
int	get_next_airstrike_frame(t_strike *strike, int offset_index);
int	get_next_barrage_frame(t_strike *strike);
int	get_next_frame(t_enemy *enemy);
int	get_next_napalm_frame(t_strike *strike, int offset_index);
int	get_pixel_color(int x, int y, int width, int height, char *data, int bpp, int line_len);
int	handle_mouse_click(int button, int x, int y, void *param);
int	handle_mouse_move(int x, int y, t_game *game);
int	handle_mouse_release(int button, int x, int y, void *param);
int	initgame(t_game **game);
int	is_close_enough(t_game *game, t_enemy *enemy);
int	is_sprite_in_front(float transformY, int stripe, int screen_width);
int	is_valid_location(t_game *game, int x, int y);
int	is_wall(t_game *game, float x, float y);
int	load_extract_texture(t_game *game, char *path);
int	load_extract_textures(t_game *game);
int	load_menu_texture(t_game *game, char *path);
int	load_pelican_inside_texture(t_game *game, char *path);
int	load_supplies_texture(t_game *game, char *path);
int	main(int argc, char **argv);
int	parse_map(t_game *game,char *cub_filepath);
int	print_2d_array(t_game *game,int ** array_to_print);
int	random_int(t_game *game, int max);
int	randomize_dead_enemy_positions(t_game *game);
int	randomize_enemy_positions(t_game *game);
int	randomize_extract_position(t_game *game);
int	randomize_uncollected_collectibles(t_game *game);
int	randomize_uncollected_supplies(t_game *game);
int	render(t_game *game);
int	respawn_player(t_game *game);
int	select_weighted_texture(t_game *game);
int	setup_game_mlx(t_game *game);
int	should_attempt_hit(unsigned long long *enemy_seed);
long	get_elapsed_microseconds(struct timeval *start, struct timeval *end);
t_ray_node	*addRay(t_ray_node **head);
t_ray_node	*calculate_rays(t_game *game, t_ray_node *list);
t_texture	*select_gun_texture(t_game *game);
t_vector2d	calculate_floor_coordinates(t_game *game, t_ray_node *center_ray);
t_vector2d	get_center_tile_coords(t_game *game);
unsigned	long long next_random(t_game *game);
unsigned	long long xorshift64(unsigned long long *state);
void	calculate_tex_values(t_ray *ray, t_texture *texture, t_game *game, double *texPos, double *step);
void	check_second_loop_end(t_game *game);
void	clean_map(t_game *game);
void	clean_player(t_game *game);
void	clean_rays(t_game *game);
void	cleanup(t_game *game);
void	cleanupAudio(void);
void	debug_print_rays(t_ray_node *head);
void	debug_texture(t_texture *texture, int x, int y);
void	draw_extract_stripe(t_game *game, int stripe, int drawStartY,
		int drawEndY, float distance);
void	free_array(int **array, int x);
void	free_floor_texture_map(t_game *game);
void	free_split_result(char **words);
void	free_wall_texture_map_path(t_game *game);
void	handle_key_3(t_game *game);
void	initialize_randomized_frames(t_game *game);
void	load_bonus_textures(t_game *game);
void	load_textures(t_game *game);
void	play_audio_on_frame(int frame_to_render);
void	play_land_voice(t_game *game);
void	printRayList(t_ray_node *head);
void	print_alive_enemies(t_game *game);
void	print_game_map(t_game *game);
void	print_map_section(t_game *game, int center_x, int center_y, int radius);
void	print_player(const t_player *player);
void	print_ray(const t_ray *ray);
void	print_vector2d(const t_vector2d *vector);
void	render_current_frame(t_game *game, int frame_to_render);
void	render_extract(t_game *game);
void	render_extract_multi_tile(t_game *game, float base_x, float base_y);
void	render_floor_rgb(t_img *img, int color);
void	render_land(t_game *game);
void	render_menu(t_game *game);
void	render_opening(t_game *game);
void	render_pelican_inside(t_game *game);
void	render_ray(t_img *img, t_ray ray, t_texture *texture, t_game *game);
void	render_respawn(t_game *game);
void	render_sky(t_game *game, char *sky_texture_path);
void	render_walls(t_game *game);
void	script_die(t_game *game);
void	setup_bonus_assets(t_game *game);
void	setup_bonus_hooks(t_game *game);
void	setup_bonus_scripts(t_game *game);
void	texture_access_check(t_game *game, int *error);
void	update_tex_pos(double *texPos, double step);
void	barrage_inbound(t_game *game);
void	cancel_supply_take(t_game *game);
void	delay_napalm_hit(t_game *game);
void	delay_strike_hit(t_game *game);
void	eagle_bombs(t_game *game);
void	eagle_inbound(t_game *game);
void	get_hit(t_game *game);
void	handle_key_1(t_game *game);
void	handle_key_2(t_game *game);
void	menu_background(t_game *game);
void	menu_background_voice(t_game *game);
void	napalm_bombs(t_game *game);
void	napalm_inbound(t_game *game);
void	play_barrage_shell(t_game *game);
void	play_bug_death(t_game *game);
void	player_burning(t_game *game);
void	remove_napalm(t_game *game);
void	reset_game_start_time(t_game *game);
void	sample_acquired(t_game *game);
void	script_board(t_game *game);
void	script_found_sth(t_game *game);
void	script_found_supplies(t_game *game);
void	script_take_supplies(t_game *game);
void	script_takeoff(t_game *game);
void	stop_barrage(t_game *game);
void	trigger_gunshots(t_game *game);
void	trigger_supply_take(t_game *game);
void	add_script(t_game *game, ScriptFunction func, int delay_seconds);
void	adjust_pitch(t_game *game, int dy, float speed);
void	apply_reduced_bump(t_game *game, float dx, float dy, float *bump_distance);
void	bump_player(t_game *game, int enemy_index);
void	calc_camera_x(t_game *game, t_ray_node *ray);
void	calc_delta_dist(t_game *game, t_ray_node *ray);
void	calc_draw_parameters(t_game *game, t_ray_node *ray);
void	calc_line_height(t_game *game, t_ray_node *ray);
void	calc_map_x(t_game *game, t_ray_node *ray);
void	calc_map_y(t_game *game, t_ray_node *ray);
void	calc_mouse_delta(int x, int y, int *last_x, int *last_y, int *dx, int *dy);
void	calc_perp_wall_dist(t_game *game, t_ray_node *ray);
void	calc_ray_dir_x(t_game *game, t_ray_node *ray);
void	calc_ray_dir_y(t_game *game, t_ray_node *ray);
void	calc_side_dist(t_game *game, t_ray_node *ray);
void	calc_texture_x(t_game *game, t_ray_node *ray);
void	calc_wall_hit(t_game *game, t_ray_node *ray);
void	calculate_and_print_center_ray(t_game *game, t_ray_node *center_ray);
void	calculate_gun_position(t_game *game, t_texture *gun_texture, int *start_x, int *start_y);
void	calculate_health_bar_dimensions(t_game *game, t_health_bar *bar);
void	calculate_rotation(t_game *game, float angle);
void	calculate_sprite_height(t_game *game, float transformY, int *spriteHeight, int *drawStartY, int *drawEndY);
void	calculate_sprite_position(t_game *game, float object_x, float object_y, float *spriteX, float *spriteY);
void	calculate_sprite_width(t_game *game, float transformY, int spriteScreenX, int *spriteWidth, int *drawStartX, int *drawEndX);
void	calculate_vector(t_game *game, int enemy_index, float *dx, float *dy);
void	check_enemy_at_center(t_game *game);
void	check_last_frame(t_game *game, int frame_to_render);
void	check_texture_loaded(t_texture *texture);
void	clean_mlx(t_game *game);
void	clean_texture(t_texture *textures, int num_textures);
void	clean_textures(t_game *game);
void	create_map_from_cub(t_game *game);
void	draw_bottom_crosshair(t_game *game, t_vector2d center);
void	draw_crosshair_line(t_game *game, t_vector2d start, t_vector2d end);
void	draw_dot(t_game *game, t_vector2d center);
void	draw_gun_pixel(t_game *game, t_texture *gun_texture, int start_x, int start_y, int x, int y);
void	draw_health_bar_border(t_game *game, t_health_bar *bar);
void	draw_health_bar_fill(t_game *game, t_health_bar *bar);
void	draw_health_bar_leftright(t_game *game, t_health_bar *bar);
void	draw_health_bar_topbottom(t_game *game, t_health_bar *bar);
void	draw_left_crosshair(t_game *game, t_vector2d center);
void	draw_right_crosshair(t_game *game, t_vector2d center);
void	draw_sprite_stripe(t_game *game, t_texture *obj_texture, int stripe, int drawStartY, int drawEndY, int spriteHeight, int spriteWidth, int spriteScreenX, float transformY);
void	draw_strike_stripe(t_game *game, int stripe, int drawStartY, int drawEndY, float distance);
void	draw_top_crosshair(t_game *game, t_vector2d center);
void	enemies_hit(t_game *game);
void	enemy_hit_attempt(t_game *game, t_enemy *enemy, int index);
void	extraction_available(t_game *game);
void	free_gun_textures(t_game *game);
void	free_texture_array(t_texture *texture_array, int num_items, t_game *game);
void	handle_key_a(t_game *game);
void	handle_key_d(t_game *game);
void	handle_key_down(t_game *game);
void	handle_key_e(t_game *game);
void	handle_key_enter(t_game *game);
void	handle_key_esc(t_game *game);
void	handle_key_left(t_game *game);
void	handle_key_right(t_game *game);
void	handle_key_s(t_game *game);
void	handle_key_up(t_game *game);
void	handle_key_w(t_game *game);
void	handle_movement_backward(t_game *game);
void	handle_movement_dash(t_game *game);
void	handle_movement_down(t_game *game);
void	handle_movement_forward(t_game *game);
void	handle_movement_left(t_game *game);
void	handle_movement_right(t_game *game);
void	handle_movement_strafe_left(t_game *game);
void	handle_movement_strafe_right(t_game *game);
void	handle_movement_up(t_game *game);
void	handle_space_shoot(t_game *game);
void	img_pix_put(t_img *img, int x, int y, int color);
void	init_last_pos(int x, int y, int *last_x, int *last_y);
void	initialize_floor_texture_map(t_game *game);
void	initialize_floor_texture_weights(t_game *game);
void	initialize_game_seed(t_game *game);
void	load_collectible_texture(t_game *game, const char *texture_path);
void	load_enemy_textures(t_game *game, const char *path_format, int num_textures);
void	load_floor_textures(t_game *game);
void	load_gun_textures(t_game *game);
void	load_land_textures(t_game *game, const char *path_format, int num_textures);
void	load_napalm_textures(t_game *game);
void	load_opening_textures(t_game *game, const char *path_format, int num_textures);
void	load_outro_textures(t_game *game, const char *path_format, int num_textures);
void	load_shooting_textures(t_game *game);
void	load_strike_textures(t_game *game);
void	load_wall_textures(t_game *game);
void	normalize_vector(float *dx, float *dy);
void	perform_dda(t_game *game, t_ray_node *ray);
void	play_gun_sound(t_game *game);
void	play_random_burn_cry(t_game *game);
void	play_random_eagle_call(t_game *game);
void	play_random_strike_sound(t_game *game);
void	player_need_stims(t_game *game);
void	print_enemy_direction(int index, float dx, float dy);
void	print_frame_info(int frame_to_render);
void	print_movement_direction(t_game *game);
void	randomize_barrage_location(t_game *game);
void	relocate_enemies(t_game *game);
void	relocate_enemy(t_game *game, t_enemy *enemy, int index);
void	render_barrage(t_game *game);
void	render_call_barrage(t_game *game, t_vector2d position);
void	render_call_strike(t_game *game, t_vector2d position);
void	render_collectible(t_game *game, t_vector2d position);
void	render_collectibles(t_game *game);
void	render_crosshair(t_game *game);
void	render_enemies(t_game *game);
void	render_enemy(t_game *game, t_enemy *enemy);
void	render_floor(t_game *game);
void	render_floor_pixel(t_game *game, int x, int y, float floorX, float floorY);
void	render_frame(t_game *game, t_texture *opening_texture);
void	render_gun(t_game *game);
void	render_health_bar(t_game *game);
void	render_hit(t_game *game);
void	render_napalm(t_game *game);
void	render_ongoing_barrage(t_game *game);
void	render_ongoing_napalm(t_game *game);
void	render_ongoing_strike(t_game *game);
void	render_outro(t_game *game);
void	render_sky_rgb(t_game *game, int color);
void	render_strike(t_game *game);
void	render_supplies(t_game *game);
void	render_supply(t_game *game, t_vector2d position);
void	render_supply_take(t_game *game);
void	rotate_player(t_game *game, float angle);
void	rotate_vector(float *x, float *y, float angle);
void	scale_gun_textures(t_game *game);
void	scale_shooting_textures(t_game *game);
void	script_barrage_enemies(t_game *game);
void	script_barrage_player(t_game *game);
void	script_napalm_enemies(t_game *game, int strike_no, float radius);
void	script_napalm_player(t_game *game, int strike_no, float radius);
void	script_skip_enter(t_game *game);
void	script_strike_enemies(t_game *game);
void	script_strike_player(t_game *game);
void	set_crosshair_position(t_game *game);
void	testscript(t_game *game);
void	transform_sprite(t_game *game, float spriteX, float spriteY, float *transformX, float *transformY);
void	trigger_extract_music(t_game *game);
void	trigger_extract_victory(t_game *game);
void	trigger_landing(t_game *game);
void	trigger_prelanding(t_game *game);
void	update_gun_state(t_game *game);
void	update_normal_gun_frame(t_game *game);
void	update_scripts(t_game *game);
void	update_shooting_gun_frame(t_game *game);


#endif
